---

- block:
    - name: "{{ name }} Post results"
      import_role:
        name: post-results
  vars:
    status: "{{ ansible_distribution_version is version(expected[name], '>=') }}"

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/checks/{{name}}/tasks/main.yml
        config_updated: {{ config_updated }}
        config_updated is not changed: {{ config_updated is not changed }}
        ansible_check_mode: {{ ansible_check_mode }}
        ansible_distribution_version: {{ ansible_distribution_version }}
        expected[name]: {{ expected[name] }}