---

- block:
    - name: "{{ name }} Post results"
      import_role:
        name: post-results
  vars:
    status: "{{ 'python3' in ansible_facts.packages and ansible_facts.packages['python3'][0].version is version(expected[name], '>=') }}"

# Doesn't work for some reason
- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/checks/{{name}}/tasks/main.yml
        ansible_facts.packages['python3'][0].version: {{ ansible_facts.packages['python3'][0].version }}
        expected[name]: {{ expected[name] }}