---

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/load_facts/tasks/main.yml BEGIN (before gather facts)

# shortcut 'ansible localhost -m ansible.builtin.setup'
- name: gather facts
  ansible.builtin.setup:
  register: facts_result

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/load_facts/tasks/main.yml MIDDLE (after gather facts)
      (that's what you get when 'ansible localhost -m ansible.builtin.setup')

- name: load environment variables
  include_vars:
    dir: "{{ playbook_dir }}/vars/{{ env | default('azure') }}"
  delegate_to: localhost
  run_once: true

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/load_facts/tasks/main.yml MIDDLE (after load environment variables)

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/load_facts/tasks/main.yml MIDDLE (after Gather the package facts)

- name: set default value to cluster_selected_checks_list
  set_fact:
    cluster_selected_checks_list: [
# Corosync
"53D035",
"156F64",
# OS and package verrsions
"CAEFF1",
"D028B9",
"9FAAD0",
"9FEFB0",
"DC5429",
"C3166E",
"222A57",
"F50AF5",
# Pacemaker
"205AF7",
"373DB8",
# SBD
"0B6DB2",
"49591F",
"816815",
"61451E",
"B089BE",
"68626E",
"A2EF8C",
# Miscellaneous
"790926",
    ]

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/load_facts/tasks/main.yml MIDDLE (after set default value to cluster_selected_checks_list)

- name: debug loaded vars
  debug:
    var: expected
    verbosity: 1

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/load_facts/tasks/main.yml END (after debug loaded vars)
#        facts_result: {{ facts_result }} # HERE: contains info about /dev
#        config_updated: {{ config_updated }} # not declared here
#        expected[name]: {{ expected[name] }} # not declared here