---

- block:
    - name: "{{ name }} Post results"
      import_role:
        name: post-results
  vars:
    status: "{{ 'sbd' in ansible_facts.packages and ansible_facts.packages['sbd'][0].version is version(expected[name], '>=') }}"

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/checks/{{name}}/tasks/main.yml
        config_updated: {{ config_updated }}
        config_updated is not changed: {{ config_updated is not changed }}
        ansible_facts.packages['sbd'][0].version: {{ ansible_facts.packages['sbd'][0].version }}
        expected[name]: {{ expected[name] }}