---

- name: "{{ name }}.check"
  shell: 'corosync-cmapctl | grep "runtime.config.totem.token (u32) = " | sed "s/^.*= //"'
  check_mode: false
  register: config_updated
  changed_when: config_updated.stdout != expected['1.1.1']

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"

- blockinfile:
    dest: /root/Workspace/ansible.txt
    marker: ""
    content: |
      roles/checks/{{name}}/tasks/main.yml
        config_updated: {{ config_updated }}
        config_updated is not changed: {{ config_updated is not changed }}
        ansible_check_mode: {{ ansible_check_mode }}